language: node.js
node_js:
  - 4.4.3
services:
  - mongodb
env:
  global:
    - NODE_ENV: test
addons:
  sauce_connect: true
notifications:
  - clausrt@outlook.com
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g protractor
  - webdriver-manager update
  - bower install
install:
  - npm install
before_script:
  - node test/data.js
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
  - node server &
  - protractor config/protractor.js